fix: parse.js script (#2)
Previously parse.js failed with the following error:
```
Error: Evaluation failed: TypeError: Illegal invocation
    at Function.values (<anonymous>)
```
because Object.values was called on a DomTokenList class which couldn't be iterated.
To fix this error and any error in the future a try catch was added.